name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install AutoHotkey
      shell: powershell
      run: |
        $cwd = (Get-Item .).FullName;
        Invoke-WebRequest "https://www.autohotkey.com/download/ahk.zip" -OutFile "$cwd\autohotkey.zip";
        Expand-Archive -Path "$cwd\autohotkey.zip" -DestinationPath "$cwd\_autohotkey\" -Force;
        Remove-Item -Path "$cwd\autohotkey.zip" -Force
        $Env:GITHUB_ENV = Write-Output ("$cwd\_autohotkey\;" + "$cwd\_autohotkey\Compiler");

    - name: Run Ahk2Exe
      shell: powershell
      run: |
        $params = ''
        if('${{inputs.in}}' -ne ''){
          $params += '/in "${{inputs.in}}" '
        }
        if('${{inputs.out}}' -ne ''){
          $params += '/out "${{inputs.out}}" '
        }
        if('${{inputs.icon}}' -ne ''){
          $params += '/icon "${{inputs.icon}}" '
        }
        ahk2exe.exe /silent $params | Write-Output
        
branding:
  color: green
  icon: terminal
